// This file documents the shape of the generated environment.ts.
// environment.ts itself is generated by scripts/write-env.mjs (gitignored)
// from CLERK_PUBLISHABLE_KEY / NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY at build time.
export const environment = {
  clerkPublishableKey: 'pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
};
