#!/usr/bin/env node
// Writes projects/docs/src/environments/environment.ts from process.env,
// so the Clerk publishable key (safe to expose client-side) can reach the
// Angular browser bundle at build time. There's no Next.js NEXT_PUBLIC_*
// auto-inlining here, so this is the SPA's substitute for that.
//
// Runs before both `ng build docs` and `ng serve` (via the prebuild:docs /
// prestart npm scripts) so the file always reflects the current environment.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

// Only Vercel Functions get `.env.local` auto-loaded; a plain Node script
// like this one does not, so parse it by hand rather than pull in dotenv.
function loadDotEnvLocal() {
  const envPath = path.join(rootDir, '.env.local');
  if (!existsSync(envPath)) return {};
  const vars = {};
  for (const line of readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

const dotEnvLocal = loadDotEnvLocal();
function readEnv(name) {
  return process.env[name] ?? dotEnvLocal[name] ?? '';
}

// Read under our own name first; fall back to the Next-flavored name the
// Clerk Vercel Marketplace integration actually provisions even for a
// non-Next project — fighting that by renaming it is fragile against
// `vercel env pull` overwriting it back.
const clerkPublishableKey =
  readEnv('CLERK_PUBLISHABLE_KEY') || readEnv('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY');

if (!clerkPublishableKey) {
  console.warn(
    '[write-env] No Clerk publishable key found in the environment — building with auth disabled.',
  );
}

const outDir = path.join(rootDir, 'projects/docs/src/environments');
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, 'environment.ts'),
  `// Generated by scripts/write-env.mjs — do not edit by hand.\nexport const environment = {\n  clerkPublishableKey: '${clerkPublishableKey}',\n};\n`,
);
